import { Slider, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    property <float> pan: 0.0;
    in-out property <int> data-serial: 0;
    pure callback render_plot(zoom: float, pan: float, data-serial: int) -> image;

    VerticalLayout {
        alignment: start;
        Image {
            source: root.render_plot(zoom-slider.value, root.pan, root.data-serial);
        }
        HorizontalLayout {
            Button {
                text: "⬅️";
                clicked => {
                    root.pan -= 1;
                }
            }
            Button {
                text: "➡️";
                clicked => {
                    root.pan += 1;
                }
            }
            zoom-slider := Slider {
                minimum: 0.1;
                maximum: 1.0;
            }
        }
    }
}
